### ISSUE TITLE
Создать сервис  доменный сервис USER_STATUS

### ISSUE THREAD

**Issue by Ledford1403** [sashapyatkov1999/logisticProgram#16]
Создать сервисы 

- get
- getAll

+ 
маппер UserStatusResponseMapper + dto  UserStatusResponse

**Comment by sashapyatkov1999** [comment]
сделал, ПРОБЛЕМЫ С GETALL

**Comment by sashapyatkov1999** [comment]
осталось поменять СREATED_AT И typeDocs, решить проблему с сервисами и продумать логику JPA
Справочники сделал

**Comment by sashapyatkov1999** [comment]
поправил еще много чего
