### ISSUE TITLE
Создать доменный сервис  Car

### ISSUE THREAD

**Issue by Ledford1403** [sashapyatkov1999/logisticProgram#20]
Добавить сервисы 

- add
- get
- getAll
- delete

+ dto + mappers

**Comment by sashapyatkov1999** [comment]
Переделал прошлую домашку , скажи, пожалуйста, какие сервисы удалить и сможешь замержить нашу работу
Залил бы в другую ветку , но там конфликт

**Comment by Ledford1403** [comment]
Не нужно делать все в одной ветке, одна задача одна ветка.  Пул реквест проверил см ошибки в нем
