### ISSUE TITLE
LB скрипты  создание таблиц

### ISSUE THREAD

**Issue by Ledford1403** [sashapyatkov1999/logisticProgram#3]
Написать LB скрипты  создание таблиц

**Comment by sashapyatkov1999** [comment]
в application.properties url не знаю верно ли указал 
а shemaInit public SchemaInitBean(DataSource dataSource, Value("LIQUIBASE") String liquiBaseSchema, ( ошибками подсвечивается, не нашел решение).
Проверить не могу из-за ошибки в shemaInit

**Comment by Ledford1403** [comment]
В мастер мы ничего не мержим без ревью,  необходимо создать ветку, на нее переключится и коммитить в нее 
![image](https://github.com/sashapyatkov1999/logisticProgram/assets/22887058/b3e98e5b-4b85-467b-93a5-c5de47655e17)

Пофиксил  конфиг,  у пути надо убрать первый слэш.

При запуске падает с ошибкой Reason: liquibase.exception.DatabaseException: Повтор имени столбца "APPLICATION_ID"
