### ISSUE TITLE
Сервисы и Контроллеры

### ISSUE THREAD

**Issue by Ledford1403** [sashapyatkov1999/logisticProgram#61]
Добавить Сервисы 

1) UserService

- login ( login, password)  true / false
- registaritation  (UserAddRequest) UserResponse
- getAll() List<UserResponse>
- get(userId) UserResponse
- delete(userId)  UserResponse
- edit(UserAddRequest) UserResponse
- search()

2) RoleService
- editRole
- deleteRole

3) DocService

- typeDocAdd
- typeDocGet
- typeDocGetAll
- typeDocDelete
- typeDocEdit
- listDocAdd
- listDocGet
- listDocGetAll
- listDocDelete
- listDocEdit

4) Application
- applicationAdd
- applicationGet
- applicationGetAll
- applicationDelete
- applicationEdit

- pointAdd
- pointGet
- pointGetAll
- pointGetByApplication
- pointDelete
- pointEdit

**Comment by sashapyatkov1999** [comment]
не забыть про editUser
